config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"

  resources :posts, only: [:index, :show, :new, :create] do
    resources :post_images, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_images

  validates_presence_of :title
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  mount_uploader :image, PostImageUploader

  belongs_to :post

  validates_presence_of :post, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = post.post_images.new(key: params[:key])
  end

  def create
    if CreatePostImage.call(post, image_params)
      redirect_to post_path(post)
      flash[:notice] = "Image was successfully added. Now it will be processed."
    else
      render action: :new
    end
  end

  private

  def post
    @post ||= Post.find(params[:post_id])
  end

  def image_params
    params.require(:post_image).permit(:name, :key)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @uploader = PostImage.new(post: @post).image
    @uploader.success_action_redirect = new_post_post_image_url(@post)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.persisted?
      redirect_to action: :index
    else
      render action: :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def post_image_url(post_image, size)
    if post_image.processed?
      post_image.image.public_send(size)
    else
      "/#{size}_placeholder.png"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDirectUpload</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="container-fluid alert-bar">
        <div class="row">
          <div class="col-md-12">
            <div id="flash_container">  
              <% if alert %>
                <div class="alert alert-danger"><%= alert.html_safe %></div>
              <% end %>
              <% if notice %>
                <div class="alert alert-success"><%= notice %></div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="row"> 
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/post_images/new.html.erb
<%= simple_form_for [:post, @post_image] do |f| %>
  <%= f.hidden_field :key %>
  <%= f.input :name %>
  <%= f.submit :submit, class: 'btn btn-sm btn-success' %>
<% end %>

app/views/posts/index.html.erb
<div>
  <h1>All Posts</h1>
  <%= link_to 'Add Post', new_post_path, class: 'btn btn-success' %>
</div>

<div class="row col-md-4">
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Title</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <th>
            <%= link_to post.title, post_path(post) %>
          </th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<div class="row col-md-6">
  <%= simple_form_for @post do |f| %>
    <%= f.input :title %>
    <%= f.button :submit, class: 'btn-success' %>
    <%= link_to 'Cancel', posts_path, class: 'btn btn-default' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div>
  <h1><%= @post.title %></h1>
  <%= link_to 'All Posts', posts_path, class: 'btn btn-default' %>
</div>

<div class="row">
  <div class="col-md-2">
    <div class="panel panel-default panel-body">
      <%= direct_upload_form_for @uploader do |f| %>
        <%= f.file_field :image %>
        <%= f.submit 'Upload Image', class: 'btn btn-sm btn-success' %>
      <% end %>
    </div>
  </div>
</div>

<div>
  <h4>Images:</h4>
  <% @post.post_images.each do |image| %>
    <%= image_tag post_image_url(image, :thumb) %>
    <p><%= image.name %></p>
  <% end %>
</div>